-- Xóa DB cũ nếu tồn tại
IF DB_ID('QuanLyQuanCafe') IS NOT NULL
BEGIN
    ALTER DATABASE QuanLyQuanCafe SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QuanLyQuanCafe;
END
GO

CREATE DATABASE QuanLyQuanCafe;
GO
USE QuanLyQuanCafe;
GO

-- Bảng Nhân viên
CREATE TABLE NhanVien
(
  MaNV NVARCHAR(100) PRIMARY KEY,
  HoTen NVARCHAR(100) NOT NULL,
  SDT CHAR(11) NOT NULL UNIQUE,
  NgayVaoLam DATE NOT NULL,
  Luong FLOAT NOT NULL,
  DiaChi NVARCHAR(200) NOT NULL
);

-- Bảng Nguyên liệu
CREATE TABLE NguyenLieu
(
  MaNL INT IDENTITY(1,1) PRIMARY KEY,
  TenNL NVARCHAR(100) NOT NULL,
  TonKho INT NOT NULL,
  DonViTinh NVARCHAR(20) NOT NULL
);

-- Bảng Nhà cung cấp
CREATE TABLE NhaCungCap
(
  MaNCC INT IDENTITY(1,1) PRIMARY KEY,
  TenNCC NVARCHAR(100) NOT NULL,
  SDT CHAR(12) NOT NULL,
  DiaChi NVARCHAR(200)
);

-- Bảng Phiếu nhập
CREATE TABLE PhieuNhap
(
  MaPN INT IDENTITY(1,1) PRIMARY KEY,
  NgayGioNhap DATETIME NOT NULL DEFAULT GETDATE(),
  MaNV NVARCHAR(100) NOT NULL,
  MaNCC INT NOT NULL,
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
  FOREIGN KEY (MaNCC) REFERENCES NhaCungCap(MaNCC)
);

-- Bảng Chi tiết phiếu nhập
CREATE TABLE ChiTietPN
(
  MaCT INT IDENTITY(1,1) PRIMARY KEY,
  SoLuong INT NOT NULL,
  DonGia FLOAT NOT NULL,
  MaPN INT NOT NULL,
  MaNL INT NOT NULL,
  FOREIGN KEY (MaPN) REFERENCES PhieuNhap(MaPN),
  FOREIGN KEY (MaNL) REFERENCES NguyenLieu(MaNL)
);

-- Bảng Khách hàng
CREATE TABLE KhachHang
(
  MaKH INT IDENTITY(1,1) PRIMARY KEY,
  HoTen NVARCHAR(100) NOT NULL,
  SDT CHAR(11) NOT NULL,
  DiemTichLuy INT NOT NULL DEFAULT 0
);

-- Bảng Sản phẩm
CREATE TABLE SanPham
(
  MaSP INT IDENTITY(1,1) PRIMARY KEY,
  TenSP NVARCHAR(100) NOT NULL,
  LoaiSP NVARCHAR(50) NOT NULL,
  DonGia FLOAT NOT NULL
);

-- Bảng Bàn
CREATE TABLE Ban
(
  MaBan INT IDENTITY(1,1) PRIMARY KEY,
  STT INT NOT NULL,
  TrangThai NVARCHAR(20) NOT NULL DEFAULT N'Trống'
);

-- Bảng Hóa đơn
CREATE TABLE HoaDon
(
  MaHD INT IDENTITY(1,1) PRIMARY KEY,
  NgayGioTao DATETIME NOT NULL DEFAULT GETDATE(),
  TruDiemTichLuy INT NOT NULL DEFAULT 0,
  MaNV NVARCHAR(100) NOT NULL,
  MaKH INT NOT NULL,
  MaBan INT NOT NULL,
  FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV),
  FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
  FOREIGN KEY (MaBan) REFERENCES Ban(MaBan)
);

-- Bảng Chi tiết hóa đơn
CREATE TABLE ChiTietHD
(
  MaCT INT IDENTITY(1,1) PRIMARY KEY,
  SoLuong INT NOT NULL,
  DaThu FLOAT NOT NULL,
  MaHD INT NOT NULL,
  MaSP INT NOT NULL,
  FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
  FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);

-- Bảng Tài khoản
CREATE TABLE TaiKhoan
(
  ID NVARCHAR(100) PRIMARY KEY,               -- chính là MaNV
  MatKhau NVARCHAR(50) NOT NULL,
  FOREIGN KEY (ID) REFERENCES NhanVien(MaNV)
);
-- Bảng Chức năng
CREATE TABLE ChucNang
(
  MaCN NVARCHAR(100) PRIMARY KEY,
  TenChucNang NVARCHAR(100) NOT NULL
);

-- Bảng Chi tiết chức năng (gán quyền cho tài khoản)
CREATE TABLE ChiTietChucNang
(
  ID NVARCHAR(100) NOT NULL,
  MaCN NVARCHAR(100) NOT NULL,
  PRIMARY KEY (ID, MaCN),
  FOREIGN KEY (ID) REFERENCES TaiKhoan(ID),
  FOREIGN KEY (MaCN) REFERENCES ChucNang(MaCN)
);
